---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://stg-api.stackbit.com/project/608802da3283cb001670604c/webhook/forestry'
sections:
- type: document
  path: site-metadata.json
  label: Site Configuration
  templates:
  - config
- type: document
  path: src/data/author.json
  label: Author
  templates:
  - author
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: '**/*'
  new_doc_ext: md
  templates:
  - advanced
  - page
  - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
